#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# install in XDG_CONFIG_HOME
# export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
# export ZDOTDIR="${ZDOTDIR:=XDG_CONFIG_HOME/zsh}"
# source "$ZDOTDIR/.zshenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
